<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div>
      <p>
        Olá, <strong>${nome}</strong>, abaixo pode encontrar as suas informações para o acesso a
        plataforma <strong>EstoqueApp</strong>
      </p>
      <p>
        Nome: <strong></strong>${nome}<br />
        User: <strong>${username}</strong> <br />
        Password: <strong>${senha}</strong> <br />
      </p>
    </div>
    <div>
      Atenciosamente,<br />
    <strong>EstoqueApp</strong>
    </div>
  </body>
</html>
